clear; clc; close all;

%% Parameters
mu = 0;              % Mean
sigma = 1;           % Standard deviation
alpha = 0.95;        % CVaR confidence level

%% VaR and CVaR
z_alpha = norminv(alpha);

% VaR for a Gaussian distribution
VaR = mu + sigma * z_alpha;

% CVaR for the upper tail of a Gaussian cost distribution
CVaR = mu + sigma * normpdf(z_alpha) / (1-alpha);

%% Gaussian distribution
x = linspace(mu-4*sigma, mu+4*sigma, 1000);
pdf = normpdf(x,mu,sigma);

%% Create figure
figure( ...
    'Color','w', ...
    'Position',[100 100 800 500]);

hold on;

%% Histogram-like bars
N = 100;

edges = linspace( ...
    mu-3.5*sigma, ...
    mu+3.5*sigma, ...
    N+1);

centers = (edges(1:end-1)+edges(2:end))/2;

heights = normpdf(centers,mu,sigma);

%% Normal region
idx_normal = centers < VaR;

bar( ...
    centers(idx_normal), ...
    heights(idx_normal), ...
    1, ...
    'FaceColor',[0 0.45 0.70], ...
    'EdgeColor','k', ...
    'LineWidth',0.3);

%% Adverse tail
idx_tail = centers >= VaR;

bar( ...
    centers(idx_tail), ...
    heights(idx_tail), ...
    1, ...
    'FaceColor',[0.85 0.05 0.05], ...
    'EdgeColor','k', ...
    'LineWidth',0.3);

%% Expected cost
xline( ...
    mu, ...
    'k-', ...
    'LineWidth',1.2);

%% VaR
xline( ...
    VaR, ...
    'k-', ...
    'LineWidth',1.2);

%% CVaR
xline( ...
    CVaR, ...
    'k-', ...
    'LineWidth',1.2);

%% Labels
% Maximum probability density
pdf_max = max(pdf);

% Gaussian height at each vertical line
pdf_mu   = normpdf(mu,mu,sigma);
pdf_VaR  = normpdf(VaR,mu,sigma);
pdf_CVaR = normpdf(CVaR,mu,sigma);

%% Expected cost label
text( ...
    mu, ...
    pdf_mu + 0.08*pdf_max, ...
    'Expected cost', ...
    'HorizontalAlignment','center', ...
    'VerticalAlignment','bottom', ...
    'FontSize',12);

%% VaR label
text( ...
    VaR + 0.08*sigma, ...
    pdf_VaR + 0.08*pdf_max, ...
    '$VaR$', ...
    'Interpreter','latex', ...
    'HorizontalAlignment','left', ...
    'VerticalAlignment','bottom', ...
    'FontSize',12);

%% CVaR label
text( ...
    CVaR + 0.08*sigma, ...
    pdf_CVaR + 0.08*pdf_max, ...
    '$CVaR$', ...
    'Interpreter','latex', ...
    'HorizontalAlignment','left', ...
    'VerticalAlignment','bottom', ...
    'FontSize',12);

%% Tail probability labels
text( ...
    (VaR+max(x))/2, ...
    -0.055, ...
    '$1-\alpha$', ...
    'Interpreter','latex', ...
    'HorizontalAlignment','center', ...
    'FontSize',12);

text( ...
    (min(x)+VaR)/2, ...
    -0.055, ...
    '$\alpha$', ...
    'Interpreter','latex', ...
    'HorizontalAlignment','center', ...
    'FontSize',12);

%% Axes labels
xlabel('Cost','FontSize',13);
ylabel('Probability distribution','FontSize',13);

%% Axis limits
xlim([mu-3.5*sigma mu+3.5*sigma]);
ylim([-0.08 pdf_max*1.20]);

%% Axis appearance
set(gca,'FontSize',11);

box off;
grid off;

ax = gca;
ax.XAxisLocation = 'bottom';
ax.YAxisLocation = 'left';

%% Force figure rendering
drawnow;
shg;

hold off;